--- 
1.7.0.3:
  url: "https://download.prestashop.com/download/releases/prestashop_1.7.0.3.zip"
  version: 1.7.0.3
1.7.0.4:
  url: "https://download.prestashop.com/download/releases/prestashop_1.7.0.4.zip"
  version: 1.7.0.4
1.7.4.4:
  url: "https://download.prestashop.com/download/releases/prestashop_1.7.4.4.zip"
  version: 1.7.4.4
  