# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.filehelper:
        class: AppBundle\Utils\FileHelper
    app.downloader:
        class: AppBundle\Utils\Downloader
        arguments: ['%app.presta_versions_download_dir%']
    app.installer:
        class: AppBundle\Utils\Installer
